### ISSUE TITLE
Image not found

### ISSUE THREAD

**Issue by hdongre-techracers** [MCROEngineering/react-native-onfido-sdk#2]
Hi I am able to build and install the app in iOS. But before the app launches it gives me an error 
- dyld: Library not loaded: @rpath/libswiftAVFoundation.dylib
/Library/Developer/CoreSimulator/Devices/5B622019-645E-43A1-B202-AF0F0022056A/data/Containers/Bundle/Application/A152515B-7F45-401E-A2BD-46279901BCD3/example.app/Frameworks/Onfido.framework/Onfido
Reason: image not found
I have tried clean and build the project. Also tried to see whether 'Always embed swift standard libraries' is set to yes.

**Comment by mdcuk34** [comment]
I had this issue and needed to downgrade Xcode to 10.1 as recommended in the Onfido React Native [example](https://github.com/onfido/onfido-sdk-react-native-sample-app#ios). Onfido currently doesn't support the 5.x.x Swift complier used in Xcode 10.2.

**Comment by alextkd** [comment]
This is closed now with https://github.com/MCROEngineering/react-native-onfido-sdk/pull/3
