### ISSUE TITLE
Workflow help

### ISSUE THREAD

**Issue by IordacheClaudiu** [MCROEngineering/react-native-onfido-sdk#4]
Hi guys,

I started to read your [tutorial](https://mcro.tech/how-to-create-react-native-wrappers-for-native-sdks/) and I was wondering what's the process of developing a wrapper around native SDKs.
For example, did you use [react-native-onfido-sdk/example/ios](https://github.com/MCROEngineering/react-native-onfido-sdk/tree/master/example/ios) to develop(debug/test) [react-native-onfido-sdk/ios](https://github.com/MCROEngineering/react-native-onfido-sdk/tree/master/ios).
I just started to read about RN and this more complex scenario...sorry if it's a dumb question.

Best regards.

**Comment by alextkd** [comment]
Hi Iordache, it's not a dumb question but this is not a place to ask for guidance in creating new SDKs, the article is pretty clear on how to do it, if you have more questions you can reach us out personally at contact@mcro.tech
